/** Public operation entry points backed by Rust and mapped to the parity ledger. */
export const OPENCV_OPERATIONS = [
  { method: "absdiff", wasmExport: "matAbsdiffU8" },
  { method: "add", wasmExport: "matAddU8" },
  { method: "addWeighted", wasmExport: "matAddWeighted" },
  { method: "bitwiseAnd", wasmExport: "matBitwiseAndU8" },
  { method: "bitwiseNot", wasmExport: "matBitwiseNotU8" },
  { method: "bitwiseOr", wasmExport: "matBitwiseOrU8" },
  { method: "bitwiseXor", wasmExport: "matBitwiseXorU8" },
  { method: "cartToPolar", wasmExport: "matCartToPolar" },
  { method: "compareEqual", wasmExport: "matCompareEqU8" },
  { method: "countNonZero", wasmExport: "matCountNonZero" },
  { method: "convertScaleAbs", wasmExport: "matConvertScaleAbs" },
  { method: "copyMakeBorder", wasmExport: "matCopyMakeBorder" },
  { method: "divide", wasmExport: "matDivide" },
  { method: "exp", wasmExport: "matExp" },
  { method: "flip", wasmExport: "matFlip" },
  { method: "grayscale", wasmExport: "grayscaleRgba" },
  { method: "hconcat", wasmExport: "matHconcat2" },
  { method: "inRange", wasmExport: "matInRangeU8" },
  { method: "log", wasmExport: "matLog" },
  { method: "lut", wasmExport: "matLut" },
  { method: "magnitude", wasmExport: "matMagnitude" },
  { method: "max", wasmExport: "matMaxU8" },
  { method: "mean", wasmExport: "matMean" },
  { method: "merge", wasmExport: "matMerge" },
  { method: "min", wasmExport: "matMinU8" },
  { method: "minMaxLoc", wasmExport: "matMinMaxLoc" },
  { method: "multiply", wasmExport: "matMultiply" },
  { method: "polarToCart", wasmExport: "matPolarToCart" },
  { method: "pow", wasmExport: "matPow" },
  { method: "resizeNearest", wasmExport: "resizeNearestRgba" },
  { method: "repeat", wasmExport: "matRepeat" },
  { method: "rotate", wasmExport: "matRotate" },
  { method: "subtract", wasmExport: "matSubtractU8" },
  { method: "split", wasmExport: "matSplit" },
  { method: "sqrt", wasmExport: "matSqrt" },
  { method: "threshold", wasmExport: "thresholdRgba" },
  { method: "transpose", wasmExport: "matTranspose" },
  { method: "trace", wasmExport: "matTrace" },
  { method: "vconcat", wasmExport: "matVconcat2" },
] as const;

/** Name of a public operation tracked by the compatibility ledger. */
export type OpenCvOperation = (typeof OPENCV_OPERATIONS)[number]["method"];
